### ISSUE TITLE
Package is taking too long to get installed

### ISSUE THREAD

**Issue by omardiaa** [KedziaPawel/matic-bridge#1]
I think it is not normal for a package to get installed in 15 minutes! Are you sure you are only included the needed packages? 

I am using Ubuntu 20.04, Node v14.18.3, trying to install the package using: `npm i --verbose @ethereumnetwork/matic-bridge` and it completed installation in: **873204ms**

**Comment by KedziaPawel** [comment]
I cannot recreate it, it installs normally on my computer. And the package size seems to be also ok. I didn't spot anything suspicious in the dependencies
